name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'task-progress-backend'
          heroku_email: ${{secrets.EMAIL}}
          usedocker: true
          appdir: backend
          healthcheck: https://task-progress-backend.herokuapp.com/health

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'task-progress-frontend'
          heroku_email: ${{secrets.EMAIL}}
          usedocker: true
          appdir: frontend
        env:
          HD_PORT: 8080
          HD_BACKEND_API: https://task-progress-backend.herokuapp.com
